In [7]:
import numpy as np

In [10]:
lst = [1,2,3,4,5]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [12]:
arr.ndim #diimensions of array

1

In [14]:
arr.shape #shape of the array

(5,)

In [16]:
arr.size

5

In [18]:
arr.dtype

dtype('int32')

In [20]:
zeros = np.zeros((3,5)) #give space in it
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
ones = np.ones((3,5)) #give space in it
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

***Reshape and RandomNumber Generator***

In [56]:
ar = np.random.random((3,3))
ar

array([[0.54259505, 0.6756397 , 0.62276421],
       [0.70635223, 0.29655433, 0.90546133],
       [0.00825388, 0.89248227, 0.45491636]])

In [58]:
np.arange(1,10,3) #here 3 is distance

array([1, 4, 7])

In [60]:
np.linspace(1,10,4) # here 4 is no.of values

array([ 1.,  4.,  7., 10.])

In [62]:
ar = np.reshape(ar, (9,1))
print(ar)

[[0.54259505]
 [0.6756397 ]
 [0.62276421]
 [0.70635223]
 [0.29655433]
 [0.90546133]
 [0.00825388]
 [0.89248227]
 [0.45491636]]


In [66]:
ar.flatten() # converts into one dimensional

array([0.54259505, 0.6756397 , 0.62276421, 0.70635223, 0.29655433,
       0.90546133, 0.00825388, 0.89248227, 0.45491636])

***Arithmetic Operations On Array***

In [69]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [73]:
print(arr+1)
print(arr-1)
print(arr*5)
print(arr/5)
print(arr**2)

[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 5 10 15 20 25 30]
[0.2 0.4 0.6 0.8 1.  1.2]
[ 1  4  9 16 25 36]


In [75]:
arr.max()

6

In [77]:
arr.min()

1

In [79]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr.max(axis=0) # column wise

array([4, 5, 6])

In [83]:
arr.min(axis=1) # row wise

array([1, 4])

In [85]:
arr.sum()

21

*Arithmetic operation on multiple arrays*

In [93]:
arr = np.array([1,2,3,4,5])
arr1=np.array([6,7,8,9,1])

In [95]:
arr+arr1

array([ 7,  9, 11, 13,  6])

In [97]:
arr.dot(arr1)

85

In [99]:
arr[:]

array([1, 2, 3, 4, 5])

In [101]:
arr[:3]

array([1, 2, 3])

In [103]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
arr[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
arr[1:2,2:3]

array([[6]])

In [109]:
arr[:,:1]

array([[1],
       [4],
       [7]])

***Sorting***

In [112]:
arr = np.array([[1,5,3],
                [6,3,8],
                [5,0,3]])
arr

array([[1, 5, 3],
       [6, 3, 8],
       [5, 0, 3]])

In [120]:
np.sort(arr,axis=0)

array([[1, 0, 3],
       [5, 3, 3],
       [6, 5, 8]])

In [126]:
np.sort(arr,axis=1,kind='mergesort')

array([[1, 3, 5],
       [3, 6, 8],
       [0, 3, 5]])

In [124]:
np.sort(arr)

array([[1, 3, 5],
       [3, 6, 8],
       [0, 3, 5]])

***Array Merging***

In [129]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
arr1 = np.array([[8,7,6,5],
                 [4,3,2,1]])

In [131]:
np.vstack((arr,arr1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [133]:
np.hstack((arr,arr1))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [141]:
ar = np.concatenate((arr,arr1),axis=0)
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [137]:
np.concatenate((arr,arr1),axis=1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [143]:
np.hsplit(ar,2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [145]:
np.vsplit(ar,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

***Slicing, Cropping and Indexing in Arrays***

In [148]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,7,5,3]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 7, 5, 3]])

***Automating using Numpy***

In [152]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [154]:
q = 0
for i in lst:
    if(i>5):
        q+=1
print(q)

5


In [156]:
lst = np.array([1,2,3,4,5,6,7,8,9,10])
lst

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [166]:
lst>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [168]:
lst[lst>5]

array([ 6,  7,  8,  9, 10])

In [170]:
len(lst[lst>5])

5

***Eye function***

In [185]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

***Empty function***

In [188]:
np.empty(shape=(5,5))

array([[8.82960296e-312, 7.65801751e-322, 0.00000000e+000,
        0.00000000e+000, 7.56571287e-307],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 1.96567549e-062],
       [1.81148490e-152, 1.13281333e-051, 1.05219790e-153,
        6.01391519e-154, 1.05237712e-153],
       [1.00630255e+141, 6.01347002e-154, 8.95402181e-096,
        1.95360725e-109, 4.90900643e+252],
       [1.94918511e-153, 6.32672800e+180, 4.74483502e+170,
        4.59210323e-072, 4.05411445e-317]])

***Random functions***

In [191]:
np.random.rand()

0.9986922466058197

In [197]:
np.random.randint(10)

3

In [209]:
np.random.randint(2,10)

5

In [211]:
np.random.randint(low=1,high=11,size=10)

array([ 7,  9, 10,  7,  8, 10,  2,  2,  4,  6])

In [217]:
np.random.randn(3)

array([-1.61459957, -0.18432492, -0.38442259])

***Reshape function -will not alter original data***

In [232]:
arr = np.random.randint(1,15,(3,4))
print(arr)
arr = arr.reshape(4,3)
print(arr)

[[ 8 14 14  6]
 [ 3  4  6  2]
 [ 7  7  5 13]]
[[ 8 14 14]
 [ 6  3  4]
 [ 6  2  7]
 [ 7  5 13]]


***Linspace function***

In [234]:
np.linspace(1,10,2)

array([ 1., 10.])

In [236]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

***flatten function***

In [243]:
arr = np.random.randint(1,15,(3,4))
print(arr.shape)
print(arr)
arr = arr.flatten()
print(arr.shape)
print(arr)

(3, 4)
[[12  5 10 13]
 [ 7  7 12 14]
 [ 2  6  7  7]]
(12,)
[12  5 10 13  7  7 12 14  2  6  7  7]


***Logspace function***

In [246]:
print(np.logspace(2,4,10))

[  100.           166.81005372   278.25594022   464.15888336
   774.26368268  1291.54966501  2154.43469003  3593.8136638
  5994.84250319 10000.        ]


In [248]:
print(np.logspace(2,4,10,base = 2))

[ 4.          4.66611616  5.44316     6.34960421  7.4069977   8.64047791
 10.0793684  11.75787594 13.71590373 16.        ]


***Copy function***

In [319]:
arr1 = np.random.randint(1,5,(3,4))
print(arr1)
arr2 = np.copy(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))
print('-'*50)

[[3 3 3 3]
 [4 1 2 4]
 [3 2 1 3]]
[[3 3 3 3]
 [4 1 2 4]
 [3 2 1 3]]
1787591273968
1787591274064
--------------------------------------------------


***min, max and sum***

In [322]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.min(axis=0))
print(arr1.min(axis=1))

4
1
32
[3 1 1 3]
[3 1 1]


***Seed function***
Generates Pseudo Random Numbers

In [325]:
np.random.seed(3)
arr = np.random.randint(1,10,(3,5))
arr

array([[9, 4, 9, 9, 1],
       [6, 4, 6, 8, 7],
       [1, 5, 8, 9, 2]])

***Sorting function***

In [9]:
np.random.seed(3)
arr = np.random.randint(1,10,(3,5))
arr.sort()
print(arr)

[[1 4 9 9 9]
 [4 6 6 7 8]
 [1 2 5 8 9]]


In [29]:
print(np.sort(arr, axis = 0))
print(np.sort(arr, axis = 1, kind = 'mergesort'))
print(arr.flatten())
print(np.sort(arr.flatten()))
arr.shape
arr = np.reshape(np.sort(arr.flatten()), arr.shape)
print(arr)

[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]
[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]
[1 1 2 4 4 5 6 6 7 8 8 9 9 9 9]
[1 1 2 4 4 5 6 6 7 8 8 9 9 9 9]
[[1 1 2 4 4]
 [5 6 6 7 8]
 [8 9 9 9 9]]


***Mathematical Operations***

In [50]:
np.random.seed(3)
arr = np.random.randint(1,10,(3,5))
print(arr)
print(arr+1)
print(arr-1)
print(arr*2)
print(arr/2)
print(arr//2)
print(arr**2)

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
[[10  5 10 10  2]
 [ 7  5  7  9  8]
 [ 2  6  9 10  3]]
[[8 3 8 8 0]
 [5 3 5 7 6]
 [0 4 7 8 1]]
[[18  8 18 18  2]
 [12  8 12 16 14]
 [ 2 10 16 18  4]]
[[4.5 2.  4.5 4.5 0.5]
 [3.  2.  3.  4.  3.5]
 [0.5 2.5 4.  4.5 1. ]]
[[4 2 4 4 0]
 [3 2 3 4 3]
 [0 2 4 4 1]]
[[81 16 81 81  1]
 [36 16 36 64 49]
 [ 1 25 64 81  4]]


In [46]:
np.random.seed(3)
arr1 = np.random.randint(1,10,(3,5))
print(arr1)
arr2 = np.random.randint(1,10,(5,3))
print(arr2)
print(arr1@arr2)
print(arr1.dot(arr2))

[[9 4 9 9 1]
 [6 4 6 8 7]
 [1 5 8 9 2]]
[[7 3 3]
 [2 4 6]
 [9 2 9]
 [8 9 2]
 [1 6 5]]
[[225 148 155]
 [175 160 147]
 [163 132 133]]
[[225 148 155]
 [175 160 147]
 [163 132 133]]


***Percentile functions***

In [72]:
np.random.seed(3)
arr1 = np.random.randint(1,10,10)
print(arr1)

[9 4 9 9 1 6 4 6 8 7]


In [74]:
arr = np.sort(arr1)
print(arr)

[1 4 4 6 6 7 8 9 9 9]


In [86]:
print(np.percentile(arr,100))
print(np.percentile(arr,25))
print(np.percentile(arr,50))
print(np.percentile(arr,75))
print(np.percentile(arr,0))
print(np.percentile(arr,20))

9.0
4.5
6.5
8.75
1.0
4.0


***Mean, Variance and Standard Deviation***

In [100]:
np.random.seed(3)
arr = np.random.randint(1,10,10)
print(arr)
print(arr.mean())
print(arr.var())
print(arr.std())

[9 4 9 9 1 6 4 6 8 7]
6.3
6.410000000000001
2.5317977802344327


***Filtering a Numpy Array***

In [109]:
arr = np.arange(1,20)
print(arr)
print(arr > 10)
print(arr[arr>10])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True]
[11 12 13 14 15 16 17 18 19]


In [111]:
arr2 = arr[arr<5]
print(arr2)

[1 2 3 4]


***Transposing An Array***

In [116]:
arr = np.random.randint(1,20,(3,5))
print(arr)
print(arr.T)

[[ 2 16 17  6 18]
 [15  1  1 10 19]
 [ 6  8  6 15  2]]
[[ 2 15  6]
 [16  1  8]
 [17  1  6]
 [ 6 10 15]
 [18 19  2]]


***Where Function***

arr = np.random.randint(1,100,10)
print(arr)
print(np.where(arr%2==0, "Even" , arr))
print(np.where(arr%2!=0, "Ood" , arr))
arr1 = np.where(arr%2==0, "Even" , arr)
arr1 = np.where(arr%2!=0, "Ood" , arr1)
print(arr1)

***Merging Arrays***

In [142]:
arr1 = np.random.randint(1,10,(2,4))
arr2 = np.random.randint(1,10,(2,4))
print(arr1)
print(arr2)
print(np.concatenate((arr1,arr2), axis = 0))
print(np.concatenate((arr1,arr2), axis = 1))

[[4 7 2 4]
 [8 5 1 9]]
[[5 8 9 6]
 [7 8 4 6]]
[[4 7 2 4]
 [8 5 1 9]
 [5 8 9 6]
 [7 8 4 6]]
[[4 7 2 4 5 8 9 6]
 [8 5 1 9 7 8 4 6]]


#vstack and hstack
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

***Splitting Arrays***

In [155]:
arr1 = np.random.randint(1,10,(4,4))
print(arr1)
print(np.vsplit(arr1,2))
print(np.hsplit(arr1,2))

[[2 6 8 6]
 [8 3 7 5]
 [9 5 4 9]
 [6 7 4 9]]
[array([[2, 6, 8, 6],
       [8, 3, 7, 5]]), array([[9, 5, 4, 9],
       [6, 7, 4, 9]])]
[array([[2, 6],
       [8, 3],
       [9, 5],
       [6, 7]]), array([[8, 6],
       [7, 5],
       [4, 9],
       [4, 9]])]


***Turning Pictures into numpy arrays***

In [159]:
from matplotlib.image import imread

In [165]:
img = imread("GFG.png")
img.shape

(192, 204, 4)

In [171]:
print(np.max(img)) #black
print(np.min(img)) #white

1.0
0.0
