# Numpy

In [3]:
import numpy as np

In [13]:
myarr = np.array([[3,4,5,6,7]], np.int8)

In [19]:
myarr[0]

array([3, 4, 5, 6, 7], dtype=int8)

In [17]:
myarr[0,1]

4

In [21]:
myarr.dtype

dtype('int8')

In [23]:
myarr[0,1] = 34

In [25]:
myarr

array([[ 3, 34,  5,  6,  7]], dtype=int8)

***Array creation in numpy***

*1. Conversion from python structures*

In [35]:
listarr=np.array([[1,2,3], [4,5,6], [7,8,9]])

In [47]:
listarr.dtype

dtype('int32')

In [49]:
listarr.shape

(3, 3)

In [41]:
listarr.size

9

In [53]:
np.array({34, 23, 23})

array({34, 23}, dtype=object)

In [55]:
zeros=np.zeros((2,5))

In [57]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
range=np.arange(15)

In [61]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
lspace=np.linspace(1,50,10)

In [65]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [69]:
emp =np.empty((4,6))

In [71]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56595733e-307, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037657e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 7.56601165e-307, 1.69118787e-306],
       [6.23058368e-307, 6.23059726e-307, 1.60220936e-306,
        9.34598925e-307, 2.22522596e-306, 1.42404727e-306]])

In [73]:
emp_like = np.empty_like(lspace)

In [75]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [85]:
ide = np.identity(3)

In [87]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
arr = np.arange(99)

In [91]:
arr = arr.reshape(3,33)

In [93]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [97]:
arr = arr.ravel()

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [101]:
arr.shape

(99,)

In [103]:
x =[[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]

In [105]:
ar = np.array(x)

In [109]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
ar.sum(axis=0)

array([12, 15, 18])

In [115]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [117]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [119]:
ar.ndim

2

In [121]:
ar.size

9

In [123]:
ar.nbytes

36

In [125]:
one = np.array([1,2,3,4,5,6])

In [127]:
one.argmax()

5

In [129]:
one.argmin()

0

In [131]:
one.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [133]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [135]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [137]:
 ar.argmin()

0

In [139]:
ar.argmax()

8

In [141]:
ar2 = np.array([[2,1,1],
               [2,1,4],
               [3,1,2]])

In [143]:
ar2

array([[2, 1, 1],
       [2, 1, 4],
       [3, 1, 2]])

In [147]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
ar + ar2

array([[ 3,  3,  4],
       [ 6,  6, 10],
       [10,  9, 11]])

In [149]:
ar * ar2

array([[ 2,  2,  3],
       [ 8,  5, 24],
       [21,  8, 18]])

In [151]:
np.sqrt(ar2)

array([[1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 2.        ],
       [1.73205081, 1.        , 1.41421356]])

In [153]:
np.sqrt(4)

2.0

In [155]:
ar2.sum()

17

In [157]:
ar2.min()

1

In [159]:
ar2.max()

4

In [161]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [163]:
type(np.where(ar<5))

tuple

In [165]:
np.count_nonzero(ar)

9

In [169]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [171]:
import sys

In [173]:
ch_ar = [0,4,55,2]

In [175]:
np_ar =np.array(ch_ar)

In [177]:
sys.getsizeof(1) * len(ch_ar)

112

In [179]:
np_ar.itemsize * np_ar.size

16

In [181]:
np_ar.tolist()

[0, 4, 55, 2]

***Numpy GFG***

**1. Converting a list to Array**

In [54]:
import numpy as np
lst = [1,2,3,4]
np.array(lst)
type(lst)
x = np.array(lst) #Numpy list to array
type(x)
v = x.tolist() #Numpy array to list
type(v)
arr = np.array(lst, ndmin = 1)
arr
arr = np.array(lst, ndmin = 3)
arr

array([[[1, 2, 3, 4]]])

**2. Arange function**

*the arange([start,], stop[, step,][, dtype]) : Returns an array with evenly space elements as per the interval.
The interval mentioned is half-opened i.e, [start, stop]*

In [60]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9


In [62]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

**3. Multidimensional Array**

In [74]:
arr = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**4. Size Function**

*In python, numpy.size() function count the number of elements along a given axis(0 - rows | 1 - colums)*

In [77]:
arr = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
arr
print("Total: ",arr.size)
print("Rows: ",np.size(arr,0))
print("Cols: ",np.size(arr,1))

Total:  9
Rows:  3
Cols:  3


**5. Shape Function**

*The Shape of an array can be defined as the number of elements in each dimensions.
Dimensions is the number of indices or subscript, that we require in order to specify an individual element of an array*

In [84]:
arr = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print((np.size(arr,0), np.size(arr,1)))
arr.shape

(3, 3)


(3, 3)

**6. Dtype Function**

*Every ndarray has an associated data type (dtyoe) object. This data type object (dtype) informs us about the layout
of the array, This means it gives us information about
1.Type of data
2.size of data
3.the byte order of data
4.if the data type is a sub-array, what is its shape and data type*

In [88]:
arr = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(arr.dtype)

int32


**7. Ndim Function**

*numpy.ndarray.ndim() function return the number of dimensions of an array*